### ISSUE TITLE
[FEATURE] 웹 접근성을 준수한다

### ISSUE THREAD

**Issue by jihyeok-um** [woowacourse-teams/2022-sokdak#624]
### 설명

웹 접근성을 준수한다.

### 세부 기능 요구사항

- [ ] 게시물의 이미지를 파일명 그대로 읽어줘서 어떤 이미지인지 알 수 없음.
- [ ] 헤더의 검색을 위한 돋보기 버튼을 사용할 수 없음
- [ ] 게시판의 이모지를 텍스트랑 구분 없이 읽음 ex) "불" HOT 게시판 "불"
- [ ] 게시물의 하트와 댓글을 생략하고 읽어버림 ex) "속닥속닥 행님들 6 6"
- [ ] 댓글창의 익명 체크박스를 "체크박스"라고 읽어버려서 용도를 알 수 없음

**Comment by yunjin-kim** [comment]
- [ ] 글 작성하는 버튼까지 tab버튼을 통해 접근할 수 없습니다.
- [ ] 더보기를 통해 게시판 내부로 접근하면 tab버튼을 통해 글에 접근할 수 없습니다
- [ ] 댓글은 작성할 수 있으나 댓글을 읽을 수는 없습니다.
