### ISSUE TITLE
[FEATURE] restAssuredMockMvc 설정추가

### ISSUE THREAD

**Issue by BETTERFUTURE4** [woowacourse-teams/2022-sokdak#88]
### 설명

`Member` 인수테스트에서 메일 요청 관련 기능을 검증하기 위해 `restAssuredMockMvc`를 사용해야 한다.
이를 위해 `build.gradle`에 해당 종속성을 추가한다.

### 세부 기능 요구사항

- [x]  `build.gradle`에 해당 종속성 추가
  - [x]  버전 호환을 위해 버전 명시하지 않음

### 주의사항
`baldung`을 따라 3.X대 버전으로 설정 시 빈 로드가 안됨.

**Comment by injoon2019** [comment]
@BETTERFUTURE4 

https://github.com/woowacourse-teams/2022-sokdak/pull/89
이 PR 한번 봐주시겠어요? RestAssuredMockMvc 관련 의존성 build.gradle에 추가했습니다.
